### ISSUE TITLE
Add Contributing guidelines

### ISSUE THREAD

**Issue by snehaM2210** [Webwiznitr/Project-Quartile#4]

**Comment by deb2000-sudo** [comment]
Step 1)Add Contributing in this Repo in the name of CONTRIBUTING.md file. 

Step 2)You can add the content of this file from this link :[Click here](https://github.com/Webwiznitr/Project-amber/blob/master/CONTRIBUTING.md).

Step 3) At the end link that CONTRIBUTING.md file to the README.md file of this project. (Refer to this link) [Click here](https://github.com/Webwiznitr/Project-amber/blob/master/README.md).

*when  you are sending Pull request you have to mention this issue no by this (Solved the issue #issue_no )*

**Comment by snehaM2210** [comment]
Well done @gouravmohanty7070 !
