### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by snehaM2210** [Webwiznitr/Project-Quartile#5]

**Comment by deb2000-sudo** [comment]
Step 1)Add Code of Conduct in this Repo in the name of CODE_OF_CONDUCT.md file. 

Step 2)You can add the content of this file from this link :[Click here](https://github.com/Webwiznitr/Project-amber/blob/master/CODE_OF_CONDUCT.md).

Step 3) At the end link that CODE_OF_CONDUCT.md file to the README.md file of this project. (Refer to this link) [Click here](https://github.com/Webwiznitr/Project-amber#readme).

*when you are sending Pull request you have to mention this issue no by this (Solved the issue #issue_no )*

**Comment by deb2000-sudo** [comment]
Komal nice work you just have to follow step 3 to close this issue. As stated in step 3 you have to update the README.md file of this project by adding the link to the CODE_OF_CONDUCT.md file of this project. For reference, you can check the README.md link of step 3 as provided earlier.
